### ISSUE TITLE
viosupgrade module doesn't wait till reboot

### ISSUE THREAD

**Issue by aklyachkin** [IBM/ansible-power-vios#50]
**Describe the bug**
The task:

```yaml
- name: Start viosupgrade
  ibm.power_vios.viosupgrade:
    cluster: false
    filename: /tmp/filelist
    post_install_binary: /tmp/postupgrade.sh
    image_file: "/mnt/{{ mksysb }}"
    mksysb_install_disks: "{{ alt_hdisk }}"
    wait_reboot: true
```

According to the documentation if wait_reboot is set to true, it waits for the system to reboot and for the upgrade to complete. (https://galaxy.ansible.com/ui/repo/published/ibm/power_vios/content/module/viosupgrade/)

In all my tests it didn't wait till reboot, but moved to the next task as soon as viosupgrade command is started.

**To Reproduce**
Create the playbook with the task and upgrade VIOS.

**Expected behavior**
It must wait till viosupgrade is finished.

**Screenshots**
As you can see on the screenshot, the whole task took 19 seconds to "perform upgrade". IRL the upgrade is still running on the server...
<img width="880" alt="grafik" src="https://github.com/IBM/ansible-power-vios/assets/3786052/54640cc1-8a57-498c-8993-ece5025508e2">
